### ISSUE TITLE
Setup milestones & release schedule

### ISSUE THREAD

**Issue by maedoc** [ins-amu/vbjax#22]
To keep expectations & issues manageable, there should be a clear version schedule, maybe a tick-tock between implementation and application. For instance

- `v0.0.x` - initial prototyping w/ Jax
- `v0.1.x` - initial TVB backend + show cases
- `v0.2.x` - field performance issues 
- `v0.3.x` - stimulation 💉
- `v0.4.x` - solver performance issues ⏳
- `v0.5.x` - generalized neural masses 🥅
- `v0.6.x` - documentation push? 📝
- `v0.7.x` - multi-connectome cases? ꙮ
- `v0.8.x` - revisit inversion use cases #5 
- ...
- `v1.0.0rc` - ~~summer break 😮‍💨🍸~~  first v1 release candidate
- `v1.0.0` - API is stable ⛱
- `v1.0.x` - fix bugs in `v1.0.x` 👾

@i-Zaak let's identify priorities/dates; it'd be nice to hit v1 by end of September

**Comment by maedoc** [comment]
Once we have a better sketch, I'll set up the milestones in the tracker here.

**Comment by i-Zaak** [comment]
Cool! I'd throw in showcase 1 use-case for v0.1. That would be any or all of following:

- paramenter sweep for MPR
- SBI with MPR
- optimization with AdEx

**Comment by maedoc** [comment]
I've mapped out the most relevant bits to milestones + issues.
